// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// Retrieve the binding value, as type Golangcilint
func (r *Binding) AsGolangcilint() *Golangcilint { // golangcilint (https://github.com/papercomputeco/daggerverse/tree/8646f8127d0bb464437e12f0a5d83d72edc211d8/golangcilint/main.go#L19)
	q := r.query.Select("asGolangcilint")

	return &Golangcilint{
		query: q,
	}
}

// Create or update a binding of type Golangcilint in the environment
func (r *Env) WithGolangcilintInput(name string, value *Golangcilint, description string) *Env { // golangcilint (https://github.com/papercomputeco/daggerverse/tree/8646f8127d0bb464437e12f0a5d83d72edc211d8/golangcilint/main.go#L19)
	assertNotNil("value", value)
	q := r.query.Select("withGolangcilintInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired Golangcilint output to be assigned in the environment
func (r *Env) WithGolangcilintOutput(name string, description string) *Env { // golangcilint (https://github.com/papercomputeco/daggerverse/tree/8646f8127d0bb464437e12f0a5d83d72edc211d8/golangcilint/main.go#L19)
	q := r.query.Select("withGolangcilintOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

type Golangcilint struct { // golangcilint (https://github.com/papercomputeco/daggerverse/tree/8646f8127d0bb464437e12f0a5d83d72edc211d8/golangcilint/main.go#L19)
	query *querybuilder.Selection

	check *string
	id    *ID
}

func (r *Golangcilint) WithGraphQLQuery(q *querybuilder.Selection) *Golangcilint {
	return &Golangcilint{
		query: q,
	}
}

// Check runs golangci-lint on the source directory without applying fixes.
// It returns the linter output as a string. If there are lint violations the
// Dagger pipeline will fail, making this suitable for CI checks.
func (r *Golangcilint) Check(ctx context.Context) (string, error) { // golangcilint (https://github.com/papercomputeco/daggerverse/tree/8646f8127d0bb464437e12f0a5d83d72edc211d8/golangcilint/main.go#L94)
	if r.check != nil {
		return *r.check, nil
	}
	q := r.query.Select("check")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// A unique identifier for this Golangcilint.
func (r *Golangcilint) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Golangcilint) XXX_GraphQLType() string {
	return "Golangcilint"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Golangcilint) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Golangcilint) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Golangcilint) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Golangcilint) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Golangcilint{query: selectNode(dag.query, id, "Golangcilint")}
	return nil
}

// Lint runs golangci-lint on the source directory with --fix, applying
// auto-fixes where possible, and returns the directory with fixes applied.
func (r *Golangcilint) Lint() *Directory { // golangcilint (https://github.com/papercomputeco/daggerverse/tree/8646f8127d0bb464437e12f0a5d83d72edc211d8/golangcilint/main.go#L80)
	q := r.query.Select("lint")

	return &Directory{
		query: q,
	}
}

// AsNode returns this Golangcilint as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Golangcilint) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// GolangcilintOpts contains options for Query.Golangcilint
type GolangcilintOpts struct {
	//
	// An optional golangci-lint configuration file (.golangci.yml) that
	// replaces the built-in opinionated defaults.
	//
	Config *File // golangcilint (https://github.com/papercomputeco/daggerverse/tree/8646f8127d0bb464437e12f0a5d83d72edc211d8/golangcilint/main.go#L56)
	//
	// Optional environment variables to set in the lint container.
	// Each entry must be in "KEY=VALUE" format (e.g. "GOEXPERIMENT=rangefunc").
	//
	EnvVars []string // golangcilint (https://github.com/papercomputeco/daggerverse/tree/8646f8127d0bb464437e12f0a5d83d72edc211d8/golangcilint/main.go#L61)
	//
	// Optional base container with golangci-lint already installed.
	// When provided it replaces the default golangci-lint image, allowing
	// callers to supply extra system libraries or tooling (e.g. sqlite-dev).
	// The container must have golangci-lint on PATH.
	//
	BaseCtr *Container // golangcilint (https://github.com/papercomputeco/daggerverse/tree/8646f8127d0bb464437e12f0a5d83d72edc211d8/golangcilint/main.go#L68)
}

// New creates a new Golangcilint module instance.
func (r *Query) Golangcilint(source *Directory, opts ...GolangcilintOpts) *Golangcilint { // golangcilint (https://github.com/papercomputeco/daggerverse/tree/8646f8127d0bb464437e12f0a5d83d72edc211d8/golangcilint/main.go#L49)
	assertNotNil("source", source)
	q := r.query.Select("golangcilint")
	for i := len(opts) - 1; i >= 0; i-- {
		// `config` optional argument
		if !querybuilder.IsZeroValue(opts[i].Config) {
			q = q.Arg("config", opts[i].Config)
		}
		// `envVars` optional argument
		if !querybuilder.IsZeroValue(opts[i].EnvVars) {
			q = q.Arg("envVars", opts[i].EnvVars)
		}
		// `baseCtr` optional argument
		if !querybuilder.IsZeroValue(opts[i].BaseCtr) {
			q = q.Arg("baseCtr", opts[i].BaseCtr)
		}
	}
	q = q.Arg("source", source)

	return &Golangcilint{
		query: q,
	}
}
